on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: demo workflow job
        run: echo This is a demo start workflow

  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: export PYTHONPATH=$PYTHONPATH:$PWD
      - run: python3 -m venv venv  # recommend using Python 3.10
      - run: source venv/bin/activate  # on Windows: venv\Scripts\activate
      - run: python3 -m pip install --upgrade pip setuptools wheel
      - run: python3 -m pip install -r requirements.txt
      - run: python3 -m pytest tests/code --verbose --disable-warnings
